INSERT INTO categoria_telefone (ID_CATEGORIA_TELEFONE, DSC_CATEGORIA_TELEFONE) VALUES (1, 'TELEFONE CELULAR');
INSERT INTO categoria_telefone (ID_CATEGORIA_TELEFONE, DSC_CATEGORIA_TELEFONE) VALUES (2, 'TELEFONE RESIDENCIAL');
INSERT INTO categoria_telefone (ID_CATEGORIA_TELEFONE, DSC_CATEGORIA_TELEFONE) VALUES (3, 'FAX');
INSERT INTO categoria_telefone (ID_CATEGORIA_TELEFONE, DSC_CATEGORIA_TELEFONE) VALUES (4, 'RAMAL');
INSERT INTO categoria_telefone (ID_CATEGORIA_TELEFONE, DSC_CATEGORIA_TELEFONE) VALUES (5, 'COMERCIAL');
