INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (0, 'Falta não justificada', '00.00');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (1, 'A disposição da Justiça Eleitoral', '01.02');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (2, 'Abono em horas', '01.47');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (3, 'Abono por esquecimento de Registro de Ponto', '01.46');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (4, 'Afastamento para acompanhar Cônjuge ou companheiro art. 84 Lei 8.112/90', '02.01');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (5, 'Afastamento para estudos ou missão no exterior Art.95 Lei 8.112/90', '01.03');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (6, 'Afastamento para exercício de mandato eletivo', '02.02');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (7, 'Afastamento para servir em organismo internacional Art. 96 Lei 8.112/90', '02.06');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (8, 'Afastamento preventivo Art. 147 Lei 8.112/90', '01.07');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (9, 'Afastamento sindicância (Suspensão)', '02.07');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (10, 'Alistamento como Eleitor Art 97, inciso III Lei 8.112/90', '01.08');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (11, 'Amamentação Art. 209 Lei 8112/90', '01.62');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (12, 'Atestado comparecimento (tratamento da própria saúde)', '01.48');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (13, 'Atestado de acompanhante (doença em pessoa da família)', '01.50');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (14, 'Atraso/Saída antecipada', '01.10');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (15, 'Ausência autorizada pela chefia imediata', '01.04');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (16, 'Ausência não justificada', '09.03');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (17, 'Ausência prevista Art.15 Lei 8.868/94', '01.11');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (18, 'Casamento Art.97, Inciso III, Alinia A, Lei 8.112/90', '01.12');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (19, 'Comparecimento a congresso, conferência ou similares (Reunião fora)', '01.13');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (20, 'Compensação', '01.14');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (21, 'Data de ingresso posterior ao dia 1º', '02.77');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (22, 'Data de ingresso posterior ao dia 1º', '03.01');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (23, 'Desligamento do estágio', '02.55');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (24, 'Dispensa por atividade eleitoral', '01.25');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (25, 'Disponibilidade ', '01.18');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (26, 'Doação voluntária de sangue Art.97, Inciso I, Lei 8.112/90', '01.19');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (27, 'Falecimento de pessoa da família Art 97, Inciso III, Alinia B, Lei 8.112/90', '01.20');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (28, 'Falta', '02.21');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (29, 'Falta por greve', '02.17');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (30, 'Férias', '01.22');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (31, 'Jurí', '01.23');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (32, 'Licença adoção ou guarda judicial Art. 210, Lei 8.112/90', '01.24');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (33, 'Licença concedida por junta médica', '02.00');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (34, 'Licença gestante Art. 207, Lei 8.112/90', '01.26');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (35, 'Licença para atividade política Art. 86, 8.112/90', '01.27');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (36, 'Licença para tratamento da própria saúde Art. 202 , Lei 8.112/90', '01.63');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (37, 'Licença paternidade Art. 208, Lei 8.112/90', '01.30');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (38, 'Licença por motivo de acidente em serviço ou doença profissional Art.211, Lei 8112/90', '01.32');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (39, 'Licença por motivo de doença em pessoa da família Art. 83, Parágrafo 2, Lei 8112/90', '01.31');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (40, 'Licença premio por assiduidade', '01.33');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (41, 'Participação em competição desportiva nacional ou no exterior Art. 102, Inciso X, Lei 8112/90', '01.35');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (42, 'Participação em processo disciplinar Art. 152, Parágrafo 1, Lei 8112/90', '01.51');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (43, 'Participação em programa de treinamento Art. 102, Inciso IV, Lei 8112/90', '01.37');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (44, 'Ponto facultativo', '03.03');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (45, 'Ponto em manutenção', '03.02');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (46, 'Serviço externo', '01.42');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (47, 'Serviço extraordinário', '01.43');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (48, 'Servidor cedido', '03.04');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (49, 'Servidor não cadastrado', '01.77');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (50, 'Sistema de frequência com defeito', '09.01');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (51, 'Sistema elétrico com defeito', '09.02');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (52, 'Substituição de cargo em comição, DAS 101.4, 101.5, 101.6', '01.61');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (53, 'Suspensão disciplinar Art. 130, Lei 8112/90', '02.25');
INSERT INTO tipo_saida (ID_TIPO_SAIDA, TXT_NOME_TIPO, TXT_CODIGO) VALUES (54, 'Viagem a serviço', '01.44');
